# Form implementation generated from reading ui file 'Run_cmd.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from multiprocessing import process
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(451, 327)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_code = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_code.setGeometry(QtCore.QRect(80, 60, 291, 61))
        self.txt_code.setObjectName("txt_code")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 441, 31))
        self.label.setObjectName("label")
        self.btn_Run = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Run.setGeometry(QtCore.QRect(100, 150, 71, 31))
        self.btn_Run.setObjectName("btn_Run")
        self.btn_Cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Cancel.setGeometry(QtCore.QRect(190, 150, 71, 31))
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 125, 301, 21))
        self.label_2.setObjectName("label_2")
        self.btn_Repeat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Repeat.setGeometry(QtCore.QRect(280, 150, 71, 31))
        self.btn_Repeat.setObjectName("btn_Repeat")
        self.txt_Cmd = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txt_Cmd.setGeometry(QtCore.QRect(20, 190, 411, 111))
        self.txt_Cmd.setObjectName("txt_Cmd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.txt_Cmd.setText = ""
        # Xử lý nút sự kiện
        self.btn_Run.clicked.connect(self.run_cmd)
        #self.btn_Cancel.clicked.connect(self.cancel_cmd)
        #self.btn_Repeat.clicked.connect(self.repeat_cmd)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">CMD Running App</span></p></body></html>"))
        self.btn_Run.setText(_translate("MainWindow", "Run"))
        self.btn_Cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#ff0000;\">Enter command code (*)</span></p></body></html>"))
        self.btn_Repeat.setText(_translate("MainWindow", "Repeat"))

    def run_cmd(self):
        import subprocess

        txt_code = self.txt_code.toPlainText()  # Lệnh Cmd

        # Khởi động subprocess với Popen
        process = subprocess.Popen(
            txt_code, shell=True, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE
        )

        # Đọc và hiển thị kết quả trong thời gian thực
        while True:
            output = process.stdout.readline()
            if output:
                self.txt_Cmd.insertPlainText(output)  # Hiển thị dòng kết quả
            elif process.poll() is not None:
                break  # Thoát vòng lặp khi lệnh kết thúc

        # Kiểm tra và hiển thị lỗi (nếu có)
        if process.returncode != 0:
            error_output = process.stderr.read()
            self.txt_Cmd.insertPlainText(f"Error: {error_output}")
    
    # Hàm xử lý nút Cancel
    # Khi cmd đang chạy ấn nút Cancel sẽ dừng cmd
    def cancel_cmd(self):
        process.terminate()
        self.txt_Cmd.insertPlainText("Command is canceled")
        if hasattr(self, 'cmd_thread') and self.cmd_thread.isRunning():  # Kiểm tra thread đang chạy
            self.cmd_thread.cancel()  # Gửi yêu cầu hủy lệnh
            self.txt_Cmd.insertPlainText("Cancel request sent. Please wait...\n")  # Hiển thị thông báo

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
